<a href="https://colab.research.google.com/github/SSAditya12/my-projects/blob/main/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])



In [ ]:
# Initialize weights and biases
#np.random.seed(42)
#w_hidden = np.random.randn(2, 2)  # 2x2 weight matrix for hidden layer
#b_hidden = np.random.randn(1, 2)  # Bias for hidden layer
#w_output = np.random.randn(2, 1)  # 2x1 weight matrix for output layer
#b_output = np.random.randn(1, 1)  # Bias for output layer
w_hidden = np.array([[-0.3, 0.5],[0.2, -0.6]])
b_hidden = np.array([0.4, 0.3])
w_output = np.array([[0.6],[-0.3]])
b_output = np.array([0.1])
w_hidden


array([[-0.3,  0.5],
       [ 0.2, -0.6]])

In [ ]:
b_hidden

array([0.4, 0.3])

In [ ]:
# Activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivatives for backpropagation
def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid_derivative(x):
    return x * (1 - x)



In [ ]:
# Training the Neural Network
learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    # Forward Pass
    hidden_input = np.dot(X, w_hidden) + b_hidden  # Hidden layer input
    hidden_output = relu(hidden_input)             # Hidden layer activation

    final_input = np.dot(hidden_output, w_output) + b_output  # Output layer input
    final_output = sigmoid(final_input)                       # Output layer activation

hidden_input

array([[ 0.4,  0.3],
       [ 0.6, -0.3],
       [ 0.1,  0.8],
       [ 0.3,  0.2]])

In [ ]:
hidden_output

array([[0.4, 0.3],
       [0.6, 0. ],
       [0.1, 0.8],
       [0.3, 0.2]])

In [ ]:
final_input

array([[ 0.25],
       [ 0.46],
       [-0.08],
       [ 0.22]])

In [ ]:
final_output

array([[0.5621765 ],
       [0.61301418],
       [0.48001066],
       [0.55477924]])

In [ ]:
# Compute Loss (Binary Cross-Entropy)
loss = -np.mean(Y * np.log(final_output) + (1 - Y) * np.log(1 - final_output))



In [ ]:
loss

0.7146096559053257

In [ ]:
   # Backpropagation
error_output = final_output - Y  # Error at output
gradient_output = error_output * sigmoid_derivative(final_output)  # Gradient for output layer

error_hidden = np.dot(gradient_output, w_output.T)  # Error at hidden layer
gradient_hidden = error_hidden * relu_derivative(hidden_output)  # Gradient for hidden layer



In [ ]:
error_output

array([[ 0.5621765 ],
       [-0.38698582],
       [-0.51998934],
       [ 0.55477924]])

In [ ]:
gradient_output

array([[ 0.1383708 ],
       [-0.09180379],
       [-0.12978956],
       [ 0.13703005]])

In [ ]:
error_hidden

array([[ 0.08302248, -0.04151124],
       [-0.05508228,  0.02754114],
       [-0.07787374,  0.03893687],
       [ 0.08221803, -0.04110901]])

In [ ]:
gradient_hidden

array([[ 0.08302248, -0.04151124],
       [-0.05508228,  0.        ],
       [-0.07787374,  0.03893687],
       [ 0.08221803, -0.04110901]])

In [ ]:
 # Update weights and biases
w_output -= learning_rate * np.dot(hidden_output.T, gradient_output)
b_output -= learning_rate * np.sum(gradient_output, axis=0, keepdims=False)

w_hidden -= learning_rate * np.dot(X.T, gradient_hidden)
b_hidden -= learning_rate * np.sum(gradient_hidden, axis=0, keepdims=False)




In [ ]:
w_output

array([[ 0.6],
       [-0.3]])

In [ ]:
# Print loss every 1000 epochs
if epoch % 100 == 0:
 print(f'Epoch {epoch}, Loss: {loss:.4f}')

In [ ]:

# Test the trained model
hidden_input = np.dot(X, w_hidden) + b_hidden
hidden_output = relu(hidden_input)

final_input = np.dot(hidden_output, w_output) + b_output
final_output = sigmoid(final_input)

print("\nFinal Predictions:")
print(final_output.round())  # Rounds predictions to 0 or 1


Final Predictions:
[[1.]
 [1.]
 [0.]
 [1.]]
